/ ************************* Banco de dados ************************* / 

/* Criando a base de dados */
- CREATE DATABASE HEALTHSCHEDULE;

/* Utilizando a base de dados */ 
- USE HEALTHSCHEDULE;

/* Criando a tabela Empresas */ 
CREATE TABLE EMPRESAS (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(200) NOT NULL,
    CNPJ VARCHAR(20) NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE
);

/* Criando a tabela de Usuários */
CREATE TABLE USUARIOS (
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    EMPRESA_ID INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    SENHA VARCHAR(200) NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE
);

ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_EMPRESAS_ID
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS (ID);

/* Criando a tabela de Consultórios */
CREATE TABLE CONSULTORIOS (
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    EMPRESA_ID INT NOT NULL,
    NOME VARCHAR(100),
    ATIVO BOOLEAN DEFAULT TRUE
);

ALTER TABLE CONSULTORIOS ADD CONSTRAINT FK_CONSULTORIOS_EMPRESAS_ID
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS (ID);

/* Criando a tabela de UsuarioxConsultorio*/
CREATE TABLE USUARIOXCONSULTORIOS (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    USUARIO_ID INT NOT NULL,
    CONSULTORIO_ID INT NOT NULL
);

ALTER TABLE USUARIOXCONSULTORIOS ADD CONSTRAINT FK_USUARIOXCONSULTORIOS_USUARIOS_ID
FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (ID);

ALTER TABLE USUARIOXCONSULTORIOS ADD CONSTRAINT FK_USUARIOXCONSULTORIOS_CONSULTORIOS_ID
FOREIGN KEY (CONSULTORIO_ID) REFERENCES CONSULTORIOS (ID);

/* Criando a tabela de Convênios */
CREATE TABLE CONVENIOS (
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    EMPRESA_ID INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    CODIGO VARCHAR(20) NOT NULL,
    ATIVO BOOLEAN
     DEFAULT TRUE
);

ALTER TABLE CONVENIOS ADD CONSTRAINT FK_CONVENIOS_EMPRESAS_ID
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS (ID);

/* Criando a tabela de ConvenioxConsultorios */
CREATE TABLE CONVENIOXCONSULTORIOS (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CONVENIO_ID INT NOT NULL,
    CONSULTORIO_ID INT NOT NULL
);

ALTER TABLE CONVENIOXCONSULTORIOS ADD CONSTRAINT FK_CONVENIOXCONSULTORIOS_CONVENIOS_ID
FOREIGN KEY (CONVENIO_ID) REFERENCES CONVENIOS (ID);

ALTER TABLE CONVENIOXCONSULTORIOS ADD CONSTRAINT FK_CONVENIOXCONSULTORIOS_CONSULTORIOS_ID
FOREIGN KEY (CONSULTORIO_ID) REFERENCES CONSULTORIOS (ID);

/* Criando a tabela de TIpos de Agendamento */
CREATE TABLE TIPOS_AGENDAMENTO (
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CONSULTORIO_ID INT NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    CONSULTA BOOLEAN NOT NULL,
    PROCEDIMENTO BOOLEAN NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE
);

ALTER TABLE TIPOS_AGENDAMENTO ADD CONSTRAINT FK_TIPOS_AGENDAMENTO_CONSULTORIOS_ID
FOREIGN KEY (CONSULTORIO_ID) REFERENCES CONSULTORIOS (ID);

/* Criando a tabela de Situacoes da Agenda */
CREATE TABLE SITUACOES_AGENDA (
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    DEFINITIVO BOOLEAN DEFAULT FALSE
);

/* Criando a tabela de Especialidades */
CREATE TABLE ESPECIALIDADES (
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CONSULTORIO_ID INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE
);

ALTER TABLE ESPECIALIDADES ADD CONSTRAINT FK_ESPECIALIDADES_CONSULTORIOS_ID
FOREIGN KEY (CONSULTORIO_ID) REFERENCES CONSULTORIOS (ID);

/* Criando a tabela de Medicos */
CREATE TABLE MEDICOS (
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(200) NOT NULL,
    CRM VARCHAR(15) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    CPF VARCHAR(20) NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE
);

/* Criando a tabela de MedicoxConsultorios */
CREATE TABLE MEDICOSXCONSULTORIO (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    MEDICO_ID INT NOT NULL,
    CONSULTORIO_ID INT NOT NULL
);

ALTER TABLE MEDICOXCONSULTORIOS ADD CONSTRAINT FK_MEDICOXCONSULTORIOS_MEDICOS_ID
FOREIGN KEY (MEDICO_ID) REFERENCES MEDICOS (ID);

ALTER TABLE MEDICOXCONSULTORIOS ADD CONSTRAINT FK_MEDICOXCONSULTORIOS_CONSULTORIOS_ID
FOREIGN KEY (CONSULTORIO_ID) REFERENCES CONSULTORIOS (ID);

/* Criando a tabela de MedicoxEspecialidades */
CREATE TABLE MEDICOXESPECIALIDADES (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    MEDICO_ID INT NOT NULL,
    ESPECIALIDADE_ID INT NOT NULL
);

ALTER TABLE MEDICOXESPECIALIDADES ADD CONSTRAINT FK_MEDICOXESPECIALIDADES_MEDICOS_ID
FOREIGN KEY (MEDICO_ID) REFERENCES MEDICOS (ID);

ALTER TABLE MEDICOXESPECIALIDADES ADD CONSTRAINT FK_MEDICOXESPECIALIDADES_ESPECIALIDADES_ID
FOREIGN KEY (ESPECIALIDADE_ID) REFERENCES ESPECIALIDADES (ID);


/* Criando a tabela de Pacientes */
CREATE TABLE PACIENTES (
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
    EMPRESA_ID INT NOT NULL,
    NOME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    DT_NASC DATE NOT NULL,
    ATIVO BOOLEAN    
);

ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTES_EMPRESAS_ID
FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS (ID);

/* Criando a tabela de PacientexEnderecos */
CREATE TABLE PACIENTEXENDERECOS (
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	PACIENTE_ID INT NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    BAIRRO VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(5),
    CEP VARCHAR(11) NOT NULL,
    PADRAO BOOLEAN DEFAULT FALSE,
    ATIVO BOOLEAN DEFAULT TRUE
);

ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTEXENDERECOS_PACIENTES_ID
FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTES (ID);


/* Criando a tabela de PacientexContatos */
CREATE TABLE PACIENTEXCONTATOS (
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    PACIENTE_ID INT NOT NULL,
    NOME VARCHAR(200) NOT NULL,
    TELEFONE VARCHAR(20),
    PADRAO BOOLEAN DEFAULT FALSE
);

ALTER TABLE PACIENTES ADD CONSTRAINT FK_PACIENTEXCONTATOS_PACIENTES_ID
FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTES (ID);

/* Criando a tabela de Agendas */
CREATE TABLE AGENDAS (
	ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ESPECIALIDADE_ID INT NOT NULL,
    CONSULTORIO_ID INT NOT NULL,
    MEDICO_ID INT NOT NULL,
    PACIENTE_ID INT NOT NULL,
    TIPOAGENDAMENTO_ID INT NOT NULL,
    CONVENIO_ID INT NOT NULL,
    SITUACAO_ID INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    RETORNO BOOLEAN DEFAULT FALSE,
    DT_AGENDA DATE NOT NULL,
    HR_INICIAL VARCHAR(8) NOT NULL,
    HR_FINAL VARCHAR(8) NOT NULL,
    OBSERVACOES VARCHAR(500)
);

ALTER TABLE AGENDAS ADD CONSTRAINT FK_AGENDAS_ESPECIALIDADES_ID
FOREIGN KEY (ESPECIALIDADE_ID) REFERENCES ESPECIALIDADES (ID); 

ALTER TABLE AGENDAS ADD CONSTRAINT FK_AGENDAS_CONSULTORIOS_ID
FOREIGN KEY (CONSULTORIO_ID) REFERENCES CONSULTORIOS (ID); 

ALTER TABLE AGENDAS ADD CONSTRAINT FK_AGENDAS_MEDICOS_ID
FOREIGN KEY (MEDICO_ID) REFERENCES MEDICOS(ID); 

ALTER TABLE AGENDAS ADD CONSTRAINT FK_AGENDAS_PACIENTES_ID
FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTES (ID); 

ALTER TABLE AGENDAS ADD CONSTRAINT FK_AGENDAS_TIPOS_AGENDAMENTO_ID
FOREIGN KEY (TIPOAGENDAMENTO_ID) REFERENCES TIPOS_AGENDAMENTO (ID); 

ALTER TABLE AGENDAS ADD CONSTRAINT FK_AGENDAS_CONVENIOS_ID
FOREIGN KEY (CONVENIOS_ID) REFERENCES CONVENIOS (ID); 

ALTER TABLE AGENDAS ADD CONSTRAINT FK_AGENDAS_SITUACOES_AGENDA_ID
FOREIGN KEY (SITUACAOAGENDA_ID) REFERENCES SITUACOES_AGENDA (ID); 

ALTER TABLE AGENDAS ADD CONSTRAINT FK_AGENDAS_USUARIOS_ID
FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (ID); 
